name: Create Release on Version Update

on:
  push:
    branches:
      - "main"

jobs:
  create-release:
    runs-on: ubuntu-22.04
    #if: github.repository == 'dianaw353/Lunur-Shell'
    continue-on-error: true
    permissions:
      contents: write # Required for creating releases/tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compare current release with project version
        id: compare_versions
        run: |
          # Check if tag already exists in remote release
          CURRENT_TAG=$(gh release view -q '.tagName' --json tagName 2>/dev/null || echo "none")
          PROJECT_VERSION=$(grep -m 1 version pyproject.toml | tr -d 'version = "' | tr -d "'" | sed 's/^/v/')
          
          if [ "$CURRENT_TAG" == "$PROJECT_VERSION" ]; then
            echo "No new release to generate!"
            echo "NEW_RELEASE=0" >> $GITHUB_ENV
            exit 0
          fi
          
          # Apparently the tag still exists when the release is deleted from GitHub web interface...
          # Also mock the exit status so that it always returns with code 0.
          git push --delete origin refs/tags/$PROJECT_VERSION || true
          echo "NEW_RELEASE=1" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run catalog script
        id: run_script
        if: ${{ env.NEW_RELEASE == '1' }}
        run: |
          # Execute the script and save the output
          if [ -x assets/scripts/GetCatalog.sh ]; then
            GH_TOKEN=$GH_TOKEN ./assets/scripts/GetCatalog.sh > release_notes.md
          else
            echo "assets/scripts/GetCatalog.sh is not executable or not found"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        id: create_tag
        if: ${{ env.NEW_RELEASE == '1' }}
        run: |
          # Generate a new tag based on the version
          TAG_NAME=$(grep -m 1 version pyproject.toml | tr -d 'version = "' | tr -d "'" | sed 's/^/v/')
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Generate proper release name title
        id: gen_proper_rel_name_title
        if: ${{ env.NEW_RELEASE == '1' }}
        run: |
          echo "$tag_name" | sed 's/^v/PROPER_RELEASE_TITLE=Version /' >> $GITHUB_ENV
        env:
          tag_name: ${{ env.TAG_NAME }}

      - name: Determine whether if we're dealing with a pre-release
        id: is_prerelease
        if: ${{ env.NEW_RELEASE == '1' }}
        run: |
          if echo "$tag_name" | grep '\-rc\|-b'; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi
        env:
          tag_name: ${{ env.TAG_NAME }}

      - name: Output release notes
        id: output_release_notes
        if: ${{ env.NEW_RELEASE == '1' }}
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release
        if: ${{ env.NEW_RELEASE == '1' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.PROPER_RELEASE_TITLE }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: ${{ env.IS_PRERELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
